env: "beta"
api:
  name: "flask_skeleton"
  port: 9290


db:
  engine: "mysql"
  user: "root"
  password: ${DB_PASSWORD}
  host: "localhost"
  port: "3306"
  schema: "flask_skeleton"

log:
  rotate:
    enabled: true
    path_file: "/tmp/logs"
    max_size: 10485760  # 1024*1024*10 = 10 MB
    backup_count: 15

  console:
    enabled: true

  level: 10 # CRITICAL = 50, ERROR = 40, WARNING = 30, INFO = 20, DEBUG = 10